name: mitoedit
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - biopython=1.84
  - pandas=2.2.3
  - openpyxl=3.1.5
  - fastapi=0.115.8
  - uvicorn=0.34.0
  - python-multipart=0.0.20
  - jinja2=3.1.5
  - requests
  - xlsxwriter
  - pip
  - pip:
    - argparse
