"""
Tests for custom-sequence alignment and bystander position liftover.

Scenario: delete 200 bases from positions 1001-1200 (1-indexed) of the
reference, then edit at position (11696 - 200) = 11496 in the custom
sequence (G→A).

Fixture files (generated by scripts/generate_test_custom_seq.py):
  tests/input/custom_seq_200bp_deletion.txt   — plain-text sequence
  tests/input/custom_seq_200bp_deletion.fa    — FASTA sequence

Expected behaviour:
  - Custom Bystander Position  == (Reference Bystander Position - 200)
  - Reference Bystander Position in the custom run matches the bystander
    positions from an equivalent reference run at position 11696.
"""

import pytest
from importlib.resources import files
from pathlib import Path

from mitoedit import process_mitoedit
from mitoedit.io import read_sequence_file

# ---------------------------------------------------------------------------
# Constants — must stay in sync with scripts/generate_test_custom_seq.py
# ---------------------------------------------------------------------------
REF_POSITION = 11696
DELETION_START = 1000         # 0-indexed, inclusive  (1-indexed pos 1001)
DELETION_END = 1200           # 0-indexed, exclusive
DELETION_SIZE = DELETION_END - DELETION_START   # 200
CUSTOM_POSITION = REF_POSITION - DELETION_SIZE  # 11496
MUTANT_BASE = "A"

_TESTS_DIR = Path(__file__).resolve().parent
_INPUT_DIR = _TESTS_DIR / "input"
_TXT_FIXTURE = _INPUT_DIR / "custom_seq_200bp_deletion.txt"
_FA_FIXTURE = _INPUT_DIR / "custom_seq_200bp_deletion.fa"


# ---------------------------------------------------------------------------
# Ensure fixture files exist (generate them if missing)
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session", autouse=True)
def ensure_fixture_files():
    """Generate test input files if they have not been created yet.

    Run ``python scripts/generate_test_custom_seq.py`` to pre-generate them,
    or let this fixture create them automatically during the test session.
    """
    if not _TXT_FIXTURE.exists() or not _FA_FIXTURE.exists():
        # Import and run the generator so the test suite is self-contained
        import sys
        _REPO_ROOT = _TESTS_DIR.parent
        if str(_REPO_ROOT) not in sys.path:
            sys.path.insert(0, str(_REPO_ROOT))
        from scripts.generate_test_custom_seq import generate
        generate(output_dir=_INPUT_DIR)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def custom_seq_from_txt():
    """Custom sequence loaded from the .txt fixture file."""
    return read_sequence_file(str(_TXT_FIXTURE))


@pytest.fixture(scope="module")
def custom_seq_from_fa():
    """Custom sequence loaded from the .fa fixture file."""
    return read_sequence_file(str(_FA_FIXTURE))


@pytest.fixture(scope="module")
def ref_result():
    """Run on the unmodified reference at position 11696 G→A."""
    return process_mitoedit(position=REF_POSITION, mutant_base=MUTANT_BASE)


@pytest.fixture(scope="module")
def custom_result(custom_seq_from_txt):
    """Run on the 200-base-deleted custom sequence (loaded from .txt) at 11496 G→A."""
    return process_mitoedit(
        position=CUSTOM_POSITION,
        mutant_base=MUTANT_BASE,
        mtdna_seq=custom_seq_from_txt,
    )


# ---------------------------------------------------------------------------
# File I/O consistency
# ---------------------------------------------------------------------------

def test_txt_and_fa_fixtures_are_identical(custom_seq_from_txt, custom_seq_from_fa):
    """Both fixture files must decode to the same sequence string."""
    assert custom_seq_from_txt == custom_seq_from_fa


def test_custom_seq_is_200_shorter_than_reference(custom_seq_from_txt):
    ref_seq = (
        files("mitoedit.resources")
        .joinpath("mito.txt")
        .read_text()
        .replace("\n", "")
    )
    assert len(custom_seq_from_txt) == len(ref_seq) - DELETION_SIZE


# ---------------------------------------------------------------------------
# Structural checks
# ---------------------------------------------------------------------------

def test_custom_windows_has_liftover_columns(custom_result):
    wdf = custom_result["windows_df"]
    assert "Reference Position of Bystanders" in wdf.columns
    assert "Window Has Indels" in wdf.columns


def test_custom_bystanders_has_both_position_columns(custom_result):
    bdf = custom_result["bystanders_df"]
    assert not bdf.empty, "Expected bystander annotations for position 11496"
    assert "Custom Bystander Position" in bdf.columns
    assert "Reference Bystander Position" in bdf.columns


def test_reference_run_has_no_liftover_columns(ref_result):
    wdf = ref_result["windows_df"]
    assert "Reference Position of Bystanders" not in wdf.columns
    assert "Window Has Indels" not in wdf.columns


# ---------------------------------------------------------------------------
# Coordinate checks
# ---------------------------------------------------------------------------

def _collect_bystander_positions(windows_df, col="Position of Bystanders"):
    """Flatten all bystander position lists from windows_df into a set."""
    return {
        pos
        for lst in windows_df[col]
        for pos in (lst if isinstance(lst, list) else [])
        if pos is not None
    }


def test_reference_bystander_positions_match_ref_run(ref_result, custom_result):
    """Reference positions reported by the custom run must equal the bystander
    positions from the reference run (both in reference coords)."""
    ref_positions = _collect_bystander_positions(ref_result["windows_df"])
    custom_ref_positions = _collect_bystander_positions(
        custom_result["windows_df"], col="Reference Position of Bystanders"
    )
    assert ref_positions, "Reference run produced no bystanders — test is vacuous"
    assert custom_ref_positions == ref_positions, (
        f"Reference bystander positions differ.\n"
        f"  Reference run:  {sorted(ref_positions)}\n"
        f"  Custom run ref: {sorted(custom_ref_positions)}"
    )


def test_custom_bystander_positions_shifted_by_deletion(ref_result, custom_result):
    """Custom bystander positions must be exactly 200 less than the corresponding
    reference positions (deletion is entirely before the edit site)."""
    ref_positions = _collect_bystander_positions(ref_result["windows_df"])
    custom_positions = _collect_bystander_positions(custom_result["windows_df"])
    assert ref_positions, "Reference run produced no bystanders — test is vacuous"
    expected = {p - DELETION_SIZE for p in ref_positions}
    assert custom_positions == expected, (
        f"Expected custom positions {sorted(expected)}, got {sorted(custom_positions)}"
    )


def test_no_indels_outside_deletion_region(custom_result):
    """Windows near position 11496 are far from the deletion (pos 1001-1200)
    and must not be flagged as containing indels."""
    wdf = custom_result["windows_df"]
    flagged = wdf[wdf["Window Has Indels"]]
    assert flagged.empty, (
        f"Unexpected indel flags on windows near position {CUSTOM_POSITION}:\n"
        f"{flagged[['Pipeline', 'Window Size', 'Position', 'Window Has Indels']]}"
    )
